import {storage,sameOrigin,eventMinimum} from '@/lib/storage';
import {estimate} from '@/data/cakesData';
const fail=(error:string,status=400)=>Response.json({error},{status});
export async function POST(request:Request){if(!sameOrigin(request))return fail('Invalid request origin.',403);if(Number(request.headers.get('content-length')||0)>6*1024*1024)return fail('Image must be smaller than 5 MB.',413);let savedKey:string|null=null;try{const form=await request.formData();const raw=form.get('data');if(typeof raw!=='string'||raw.length>15000)return fail('Please check your request details.');let d;try{d=JSON.parse(raw)}catch{return fail('Invalid request details.')}
if(typeof d.requestId!=='string'||! /^[a-f0-9-]{36}$/i.test(d.requestId))return fail('Please refresh this page and try again.');
for(const [key,max] of Object.entries({name:100,email:254,phone:25,city:100,notes:3000,address:1000,message:80,type:100,flavor:100,finish:100,color:100,method:100,date:10,design:100,size:20,kind:30})){if(d[key]!==undefined&&(typeof d[key]!=='string'||d[key].length>max))return fail('Please check '+key+'.');}
if(!d.name?.trim()||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email||'')||! /^[+0-9 ()-]{7,25}$/.test(d.phone||'')||!d.city?.trim())return fail('Please enter your name, a valid email, phone and city.');
if(!/^\d{4}-\d{2}-\d{2}$/.test(d.date||'')||isNaN(Date.parse(d.date))||d.date<eventMinimum())return fail('Please select an event date at least 2 days ahead.');
const allowed=['Custom cake','Birthday cake','Wedding cake','Gift hamper','Cupcakes & treats','Corporate order'];if(!allowed.includes(d.type)||!['custom-order','contact'].includes(d.kind))return fail('Please choose a valid order type.');
if(d.kind==='custom-order'&&(!['small','medium','large'].includes(d.size)||!['Vanilla','Chocolate','Red velvet','Coffee'].includes(d.flavor)||!['Simple & elegant','Floral & gold details','Personalised topper'].includes(d.finish)||!['Delivery','Collection'].includes(d.method)))return fail('Please complete all order steps.');
if(d.method==='Delivery'&&!d.address?.trim())return fail('Please add your delivery address.');if(d.kind==='contact'&&!d.notes?.trim())return fail('Please add a message.');
const {DB,BUCKET}=storage();const existing=await DB.prepare('SELECT id FROM inquiries WHERE id = ?').bind(d.requestId).first();if(existing)return Response.json({id:d.requestId});
const file=form.get('reference');if(file instanceof File&&file.size){if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))return fail('Choose a JPG, PNG or WebP image smaller than 5 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const valid=(file.type==='image/jpeg'&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)||(file.type==='image/png'&&bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71)||(file.type==='image/webp'&&new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP');if(!valid)return fail('This file does not appear to be a supported image.');savedKey='references/'+d.requestId;await BUCKET.put(savedKey,bytes,{httpMetadata:{contentType:file.type}})}
const details={...d,estimate:d.kind==='custom-order'?estimate(d):null,pricing:'illustrative; requires confirmation'};await DB.prepare('INSERT INTO inquiries (id,name,email,phone,kind,details,reference_key,created_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(d.requestId,d.name.trim(),d.email.trim().toLowerCase(),d.phone,d.kind,JSON.stringify(details),savedKey,new Date().toISOString()).run();return Response.json({id:d.requestId},{status:201});
}catch(e){console.error('Inquiry save failed',e);return fail('We could not save your request. Your details are still here—please try again or message us on Facebook.',503)}}
