'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {PageHead,Img} from '@/components/bakery/shared';
import {Field,Pick,Choices,Upload,Saved,sendInquiry,minDate,newRequestId} from '@/components/bakery/forms';
import {cakesData,flavors,estimate,money} from '@/data/cakesData';
const types=[{value:'Custom cake',image:'rose-cake',detail:'Your ideas, beautifully baked'},{value:'Birthday cake',image:'birthday-heart',detail:'Make their day special'},{value:'Wedding cake',image:'rose-detail',detail:'A bespoke wedding enquiry'},{value:'Gift hamper',image:'gift-hamper',detail:'A thoughtful little surprise'},{value:'Cupcakes & treats',image:'gift-collection',detail:'Cupcakes, cookies & doughnuts'},{value:'Corporate order',image:'chocolate-bouquet',detail:'Gifting with a personal touch'}];
const sizes=[{value:'small',label:'2–4 servings',detail:'A little celebration'},{value:'medium',label:'5–8 servings',detail:'Gather your favourites'},{value:'large',label:'10+ servings',detail:'For your bigger moments'}];
const initial={type:'Custom cake',size:'medium',flavor:'Vanilla',finish:'Simple & elegant',color:'Blush pink',message:'',notes:'',method:'Delivery',date:'',city:'Karachi',address:'',name:'',email:'',phone:'',design:''};
export default function Order(){const [o,setO]=useState(initial);const [step,setStep]=useState(0);const [file,setFile]=useState(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [saved,setSaved]=useState('');const requestId=useRef('');const form=useRef(null);const update=(k,v)=>setO(s=>({...s,[k]:v}));useEffect(()=>{requestId.current=newRequestId();const q=new URLSearchParams(window.location.search),design=cakesData.find(c=>c.id===q.get('design'));setO(s=>({...s,type:types.some(t=>t.value===q.get('type'))?q.get('type'):design?.category==='Gift Hampers'?'Gift hamper':s.type,size:sizes.some(t=>t.value===q.get('size'))?q.get('size'):s.size,design:design?.id||'',notes:design?'Inspired by '+design.name:''}))},[]);const selected=cakesData.find(c=>c.id===o.design);const preview=selected?.image||types.find(t=>t.value===o.type)?.image||'rose-cake';const total=estimate(o);const steps=['Type','Size','Flavour','Details','Delivery','Confirm'];async function next(e){e.preventDefault();setError('');if(step<5){setStep(step+1);return}setBusy(true);try{const id=await sendInquiry({...o,kind:'custom-order'},file,requestId.current);setSaved(id)}catch(e){setError(e.message||'Could not save. Please try again.')}finally{setBusy(false)}}return <><PageHead label="YOUR CELEBRATION STARTS HERE" title={<>A little imagination.<br/><em>Something all yours.</em></>}>Tell us what you have in mind. We’ll turn your ideas into a personal quote.</PageHead><section className="wrap section order-layout" style={{paddingTop:20}}><div className="panel">{saved?<Saved id={saved}/>:<><div className="flex justify-between mb-4"><span className="eyebrow !mb-0">CREATE YOUR ORDER</span><span className="fine">Step {step+1} of 6</span></div><Progress value={(step+1)/6*100} aria-label="Order progress"/><div className="step-labels">{steps.map((s,i)=><span className={i===step?'current':''} key={s}>{i+1}. {s}</span>)}</div><form ref={form} onSubmit={next}>
{step===0&&<><h3>What are we celebrating?</h3><p>Choose a starting point for your creation.</p><Choices label="Cake type" value={o.type} onChange={v=>update('type',v)} options={types}/></>}
{step===1&&<><h3>A slice for everyone.</h3><p>{['Gift hamper','Cupcakes & treats'].includes(o.type)?'Choose the group size. Include the quantity you need in your notes.':'How many people are joining the celebration?'}</p><Choices label="Size and servings" value={o.size} onChange={v=>update('size',v)} options={sizes}/><p className="fine mt-5">For 10+ servings, add your exact guest count in the special requests. Larger orders are quoted individually.</p></>}
{step===2&&<><h3>Choose your flavour.</h3><p>A favourite flavour makes it even more personal.</p><Choices label="Flavour preference" value={o.flavor} onChange={v=>update('flavor',v)} options={flavors.map(value=>({value,detail:value==='Red velvet'?'+ PKR 500 illustrative estimate':'Subject to availability'}))}/><p className="fine mt-5">For hampers, this is an optional preference for baked treats. Final contents will be agreed with Afshan.</p></>}
{step===3&&<><h3>It’s all in the details.</h3><Pick label="Decoration style" value={o.finish} onChange={v=>update('finish',v)} options={['Simple & elegant','Floral & gold details','Personalised topper']}/><Pick label="Colour palette" value={o.color} onChange={v=>update('color',v)} options={['Blush pink','Ivory & gold','Burgundy','Chocolate','Custom colours']}/><Field label="Message on the cake or gift" value={o.message} onChange={e=>update('message',e.target.value)} maxLength={80} placeholder="Happy Birthday, ..."/><Field label="Special requests & exact guest count"><textarea value={o.notes} onChange={e=>update('notes',e.target.value)} maxLength={3000} placeholder="Colours, flowers, dietary needs, allergies or an idea you love..."/></Field><Upload file={file} setFile={setFile} setError={setError}/></>}
{step===4&&<><h3>When and where?</h3><p>Please allow at least 2 days. Your date is subject to confirmation.</p><Pick label="Delivery or collection" value={o.method} onChange={v=>update('method',v)} options={['Delivery','Collection']}/><Field label="Event date" type="date" min={minDate()} required value={o.date} onChange={e=>update('date',e.target.value)}/><Field label="City" value={o.city} readOnly/>{o.method==='Delivery'?<Field label="Delivery address"><textarea required maxLength={1000} value={o.address} onChange={e=>update('address',e.target.value)} placeholder="Area, street and complete address in Karachi"/></Field>:<p className="notice">Your collection location and time will be shared when your order is confirmed.</p>}<p className="fine">Delivery charges are quoted separately.</p></>}
{step===5&&<><h3>Let’s make it happen.</h3><div className="formgrid"><Field label="Your name" required maxLength={100} value={o.name} onChange={e=>update('name',e.target.value)}/><Field label="Phone / WhatsApp" type="tel" required pattern="[+0-9 ()-]{7,25}" title="Enter a valid phone number with 7–25 characters" value={o.phone} onChange={e=>update('phone',e.target.value)}/><Field label="Email address" type="email" required maxLength={254} value={o.email} onChange={e=>update('email',e.target.value)} wide/></div><div className="notice"><strong>Your request</strong><p className="!mb-0">{o.type} · {sizes.find(s=>s.value===o.size)?.label} · {o.flavor}<br/>{o.finish} · {o.color}<br/>{o.method} in {o.city} · {o.date}<br/>{file?'Reference image: '+file.name:'No reference image attached.'}</p></div><p className="fine mt-5">By sending, you agree to share these details with Baked by Afshan to discuss your order. This is a quote request; no payment is taken and no date is reserved.</p></>}
{error&&<p role="alert" className="error mt-5">{error}</p>}<div className="actions justify-between"><button type="button" className="btn secondary" disabled={step===0||busy} onClick={()=>{setError('');setStep(step-1)}}><ArrowLeft size={16}/>Back</button><button type="submit" className="btn" disabled={busy}>{busy?'Saving your request…':step===5?'Send quote request':'Continue'}<ArrowRight size={16}/></button></div></form></>}</div><aside className="preview"><div className="eyebrow">YOUR CREATION, TAKING SHAPE</div><Img name={preview} alt="An inspiration photo for your selected creation"/><p className="preview-message" style={{background:({'Blush pink':'#f8e1e5','Ivory & gold':'#efe3c6','Burgundy':'#ead4d6','Chocolate':'#e7d5c5'})[o.color]||'#f8e1e5'}}>{o.message||'Made with love, just for you.'}</p><p className="fine mt-3">Inspiration photo. Final design is agreed with Afshan.</p><dl><dt>Creation</dt><dd>{o.type}</dd><dt>Guests</dt><dd>{sizes.find(s=>s.value===o.size)?.label}</dd><dt>Flavour</dt><dd>{o.flavor}</dd><dt>Palette</dt><dd>{o.color}</dd><dt>Finish</dt><dd>{o.finish}</dd></dl><div className="borderline" aria-live="polite"><div className="eyebrow !mb-2">ILLUSTRATIVE ESTIMATE</div><div className="price">{money(total)}</div><p className="fine">Not a confirmed price. Final cost depends on size, ingredients, design and delivery. Wedding and corporate orders are quoted individually.</p></div></aside></section></>}
