'use client';
import {useEffect,useState} from 'react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {business} from '@/data/business';
export function Field({label,children,...props}){return <label className={'field '+(props.wide?'wide':'')}>{label}{children||<input {...Object.fromEntries(Object.entries(props).filter(([k])=>k!=='wide'))}/>}</label>}
export function Pick({label,value,onChange,options}){return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full h-12 rounded-sm bg-[#fffdf9] text-sm"><SelectValue/></SelectTrigger><SelectContent>{options.map(x=><SelectItem value={typeof x==='string'?x:x.value} key={typeof x==='string'?x:x.value}>{typeof x==='string'?x:x.label}</SelectItem>)}</SelectContent></Select></div>}
export function Choices({label,value,onChange,options}){return <RadioGroup aria-label={label} value={value} onValueChange={onChange} className="selection-grid">{options.map((o,i)=><label className={'choice '+(value===o.value?'selected':'')} key={o.value}><RadioGroupItem value={o.value}/>{o.image&&<img src={'/images/'+o.image+'.webp'} alt=""/>}<span>{o.label||o.value}{o.detail&&<small>{o.detail}</small>}</span></label>)}</RadioGroup>}
export function Upload({file,setFile,setError}){const [url,setUrl]=useState('');useEffect(()=>{if(!file){setUrl('');return}const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u)},[file]);return <><Field label="Reference image (optional)"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f&&(f.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))){setError('Choose a JPG, PNG or WebP image smaller than 5 MB.');e.target.value='';setFile(null);return}setError('');setFile(f||null)}}/></Field><p className="fine">JPG, PNG or WebP · up to 5 MB. Only upload images you have permission to share.</p>{url&&<div><img src={url} alt="Your uploaded reference" className="upload-preview"/><button type="button" className="textlink mb-5" onClick={()=>setFile(null)}>Remove reference</button></div>}</>}
export function Saved({id}){return <div className="success" role="status"><h3>Your request is saved. ♡</h3><p>Reference: <strong>{id}</strong></p><p>This is an enquiry, not a confirmed booking. Please message Afshan on Facebook with this reference to arrange your quote and confirm the date.</p><a className="btn" href={business.facebook} target="_blank" rel="noreferrer">Continue on Facebook ↗</a></div>}
export async function sendInquiry(data,file,key){const body=new FormData();body.set('data',JSON.stringify({...data,requestId:key}));if(file)body.set('reference',file);const r=await fetch('/api/inquiries',{method:'POST',body});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to save your request. Please try again.');return result.id}
export function minDate(){const date=new Date(Date.now()+2*86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
export function newRequestId(){if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,v=>v.toString(16).padStart(2,'0')).join('');return [h.slice(0,8),h.slice(8,12),h.slice(12,16),h.slice(16,20),h.slice(20)].join('-')}
